### ISSUE TITLE
[discussion] Remove Nightshade Finality Gadget

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/NEPs#54]
Context: there's a fundamental issue between Doomslug and NFG that we discovered recently. Specifically, it could be that a block at height h is produced, and some participants have already sent endorsements for it, and then a block at height less than h is produced but with a higher NFG score, and becomes the head. The chain stalls because no block producer can send a skip message that will bypass h.

The solution to it is to make Doomslug aware of the score, and change the conditions for endorsements and skips to accommodate it. However, since both safety and liveness proof of Doomslug rely on head height never getting lower, enduring safety and liveness remain after introducing this change is not trivial.

I instead suggest to completely remove NFG, and change Doomslug so that it
a) becomes a BFT consensus
b) loses its ability to provide some weaker sense of finality at 50%.

The full argument is here: https://docs.google.com/document/d/10uBwpEN3ADDkL9iY52K0zM1edgxmoO8hJBqxmDafFN0/

**Comment by abacabadabacaba** [comment]
What happens if a malicious producer makes two different blocks at the same height? It is possible that 40% of validators will send an endorsement for one version of the block, and 40% of validators will send an endorsement for another version. Only one validator made a slashable action. AFAIK, the consensus will stall, because no block can get 67% endorsements, and 67% won't skip either.

**Comment by abacabadabacaba** [comment]
What if we change Doomslug to get rid of the problem? Currently, we slash block producers if they produce two different blocks at the same height, or both endorse and skip a block at the same height. I suggest to change it like this: if there happens to be two blocks that are Doomslug-final such that neither of them is an ancestor of the other, then endorsements and skips on top of one block should be independent from endorsements and skips on top of the other block. That is, two endorsements or an endorsement and a skip shouldn't lead to slashing if they are on top of different blocks. This shouldn't harm Doomslug's safety (for two such blocks to even appear, at least one producer must already be slashed). In NFG, we must require that only Doomslug-final blocks may get approvals. Then, if there is a block with score _s_, there must be a Doomslug-final block with score at least _s_. This means that it should always be possible to build on top of the chain with the maximum score.

**Comment by bowenwang1996** [comment]
@abacabadabacaba I believe it is possible that neither block at height h nor the block whose height is less than h has doomslug finality while the block at height less than h has higher NFG score.

**Comment by abacabadabacaba** [comment]
@bowenwang1996 What I'm saying is that I think that it is possible to modify Doomslug and NFG so that to produce blocks with Doomslug finality on top of some block with the highest NFG score. This will solve the problem.

Conversely, I don't see a way to make Doomslug a BFT consensus by itself. The solution presented above doesn't have liveness, as I shown in the first comment.

**Comment by bowenwang1996** [comment]
> @bowenwang1996 What I'm saying is that I think that it is possible to modify Doomslug and NFG so that to produce blocks with Doomslug finality on top of some block with the highest NFG score. This will solve the problem.

Okay I understand what you meant now. But I still don't follow your argument about why the suggested approach doesn't work. One participant getting slashed doesn't necessarily stall the consensus. For doomslug endorsing one block on one fork doesn't prevent you from endorsing another block on another fork at a different height.

**Comment by SkidanovAlex** [comment]
> What happens if a malicious producer makes two different blocks at the same height? It is possible that 40% of validators will send an endorsement for one version of the block, and 40% of validators will send an endorsement for another version. Only one validator made a slashable action. AFAIK, the consensus will stall, because no block can get 67% endorsements, and 67% won't skip either.

If there are two blocks at height `h`, and both have 40% of endorsements, then the block at `h+1` cannot be produced. In 2 seconds all the honest block producers send a message to skip the block at height `h+1` and the block at height `h+2` is produced. Liveness is not violated.
