### ISSUE TITLE
Write a spec for GC

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/NEPs#61]
The corresponding work item: nearprotocol/nearcore#2596

**Comment by bowenwang1996** [comment]
Why does GC need a spec? It is strictly not part of the protocol.

**Comment by ailisp** [comment]
@bowenwang1996 talked to @SkidanovAlex he think we still need specs for our implementation specific feature like GC but not as part of "protocol spec"

**Comment by bowenwang1996** [comment]
@ailisp then it should not be in this repo. We can discuss where this should go (can potentially have it in nearcore wiki or some nearcore specific documentation).

**Comment by mfornet** [comment]
While it is not strictly mandatory implementing GC (or implementing in the way we are doing it) having a spec for GC is important for several reasons from my POV. 
- Running a node without GC will require higher harder requirements (so potentially a node is not able to run without it by default).
- GC Spec is responsible to explain what parts can be pruned away.
I'm not familiar enough with GC, but it can be the case that:
- the design of chain takes into account our GC implementation, so this spec is a very good place to explain how to implement performant GC.

I agree, that we should tag this spec as not mandatory/recommended, but still think this is a great place to keep it.

**Comment by bowenwang1996** [comment]
> design of chain is adapted to take into account our GC implementation

This is not the case and should not be the case. GC design should be specific to the implementation of the client. As along as chain is designed in a way to tolerate potential gc, it is fine. 

> this is a great place to keep it

As I said, we should only put the spec of the protocol here. Unless we somehow think GC is part of the protocol (which I disagree with), we should not put gc related stuff here.

**Comment by ailisp** [comment]
Wrote a private one in notion for now
