### ISSUE TITLE
Typo in reward formula "Economics - NEAR Protocol Specification"

### ISSUE THREAD

**Issue by 48cfu** [nearprotocol/NEPs#86]
Reading the NEAR Protocol Specification paper available at [https://nomicon.io/Economics/README.html](https://nomicon.io/Economics/README.html) I came across the error in the reward formula for a given epoch ```t```. The document's source is located at [/docs/Economics/README.html](https://github.com/nearprotocol/NEPs/blob/master/docs/Economics/README.html). 

In [Line 190](https://github.com/nearprotocol/NEPs/blob/master/docs/Economics/README.html#L190) the reward formula is calculated with ```1 - REWARD_PCT_PER_YEAR``` i.e.

```
reward[t]  = totalSupply[t] * ((1 - REWARD_PCT_PER_YEAR) ** (1/EPOCHS_A_YEAR) - 1)
```
In [Line 297](https://github.com/nearprotocol/NEPs/blob/master/docs/Economics/README.html#L297) the reward formula is calculated with ```1 + REWARD_PCT_PER_YEAR``` 
```
reward[t]  = totalSupply[t] * ((1 + REWARD_PCT_PER_YEAR) ** (1/EPOCHS_A_YEAR) - 1)
```

The latter formula should be the correct one.

**Comment by chadoh** [comment]
Fixed by #88 – please reopen if I misunderstood!
