### ISSUE TITLE
state_sync.py triggers read timeout during store validity checks

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/NEPs#91]
See state_sync.py failures here:

http://nightly.neartest.com/run/master_06b21f724204626db490f6062999a5832c323b01_20200710_124728

Note that the test finished and gets to the store valitity checks, and then triggers the read timeouts reported in the stderr

**Comment by bowenwang1996** [comment]
Should this issue be moved to https://github.com/nearprotocol/nearcore?

**Comment by Kouprin** [comment]
https://github.com/nearprotocol/nearcore/issues/2981
